#2665 delete filterred logs, not delete all
nukeviet/nukeviet pull request #3005
Opened 2020-11-20 10:48 UTC by quocdatit

I get listall records by id, implode them to string, using bulk action to delete there records

2020-11-20 12:46 UTC, quocdatit commented
Can you review to merge my code to develop @vuthao

2020-11-25 02:36 UTC, hoaquynhtim99 requested changes
Bạn check mấy cái comment này nhé. Ngoài ra bên dưới bạn có xóa một loạt các file trên kho code như thế chưa được mấy file đó được sử dụng trong dữ liệu mẫu, nếu xóa cài lên sẽ không thấy ảnh gì.

2020-11-25 02:36 UTC, hoaquynhtim99 commented on .gitignore
> +.vs
@quocdatit bạn sửa cái này lại nhé thêm `/` bên trước. Nếu để thế này thì nó sẽ ignore mọi file đó trong mọi thư mục => Không cần thiết, trong khi file đó chỉ xuất hiện ở thư mục gốc

2020-11-25 02:36 UTC, hoaquynhtim99 commented on .gitignore
> +/src/data/config/config_global.php
File này là file có index trên hệ thống nên thêm dòng này không có tác dụng, bạn tham khảo cái `git update-index --assume-unchanged` https://writeblabla.com/blog/huy-theo-doi-cac-file-tren-kho-local-nhung-khong-xoa-tren-kho-remote.html

2020-11-25 02:36 UTC, hoaquynhtim99 commented on .gitignore
> +/src/data/config/robots.php
File này cũng tương tự config_global.php bên trên

2020-11-25 03:29 UTC, quocdatit commented
Em close PR chỉnh sửa rồi tạo lại nha

2020-11-25 03:29 UTC, closed without merging