#2993 add function xml_entity_decode
nukeviet/nukeviet pull request #3006
Opened 2020-11-24 08:58 UTC by quocdatit

2020-11-25 03:59 UTC, hoaquynhtim99 commented
@quocdatit mình thấy thêm đoạn code này không cần thiết, mình check thấy nguyên nhân là file config.ini chưa thiết lập `encoding="UTF-8"`

Đơn giản chỉ cần mở hết các file config.ini của giao diện lên sửa 

```
<?xml version='1.0'?>
```

Thành

```
<?xml version="1.0" encoding="UTF-8"?>
```

Là xong

2020-11-25 06:08 UTC, quocdatit commented
ok anh, em update lại rồi

2020-11-26 03:14 UTC, hoaquynhtim99 requested changes

2020-11-26 03:14 UTC, hoaquynhtim99 commented on modules/news/global.functions.php
> +}
@quocdatit chỗ này thiếu 1 dòng trống kết thúc file. NukeViet theo chuẩn PSR-12, file kết thúc phải bằng 1 ký tự LF bạn sửa lại nhé. Xem thêm chuẩn ở đây https://www.php-fig.org/psr/psr-12/ 

> All PHP files MUST end with a non-blank line, terminated with a single LF.

2020-11-26 03:14 UTC, hoaquynhtim99 commented on themes/default/config.ini
> +
Bên dưới mình thấy bạn xóa hết các dòng trống, chỗ này lại để, nếu xóa hết bên dưới thì mình nghĩ chỗ này cũng cần xóa luôn

2020-11-26 08:01 UTC, quocdatit commented
Done nha anh @hoaquynhtim99

2020-11-26 08:35 UTC, hoaquynhtim99 approved these changes

2020-11-26 08:36 UTC, merged

2020-11-27 01:30 UTC, vuthao commented
@hoaquynhtim99 nếu thế cần sửa thêm cả ở chỗ sau
https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/admin/extensions/manage.php#L173
Đoạn: <?xml version='1.0'?>

2020-11-27 02:01 UTC, hoaquynhtim99 commented
@vuthao em đã sửa thêm cho tất cả các chỗ https://github.com/nukeviet/nukeviet/commit/ab5172fcd1cc32549f1bfce66cdb03743421b974