Develop
nukeviet/nukeviet pull request #3007
Opened 2020-11-25 05:56 UTC by quocdatit

2020-11-25 06:08 UTC, quocdatit commented
@hoaquynhtim99 check lại giúp em nhé

2020-11-27 02:15 UTC, hoaquynhtim99 commented
@quocdatit 

Các phần khác đã ok, còn lại phần chính thì chưa tối ưu. Nguyên nhân như sau:

Trong cách của bạn sửa bạn lấy toàn bộ các ID tìm kiếm được xuất ra giao diện rồi submit cái id list đó để xóa. Có hai vấn đề:
1. Sẽ phải lấy hết các bản ghi trong CSDL để lấy ID, nếu dữ liệu tìm kiếm lớn (ví dụ tìm được 20k kết quả) thì sẽ rất nặng cho MySQL
2. Data submit đi được quá lớn: Ví dụ có ID list khoảng 20k rows, mỗi id chiếm 5 con số thì có tới khoảng ~120k kí tự được xuất ra trình duyệt và gửi đi => Không tối ưu.

Nếu bạn sửa tiếp cho tối ưu bạn có thể tham khảo hướng sau: 

- Lấy điều kiện tìm kiếm trong SQL cái đoạn WHERE ..... ấy mã hóa, xuất ra trình duyệt.
- Truyền cái đoạn mã hóa đó khi gửi dữ liệu xóa.
- Giải mã cái dữ liệu tìm kiếm được để lấy ra điều kiện WHERE trong CSDL.
- Dùng điều kiện đó để chạy lệnh xóa.

Chú ý khi mã hóa, giải mã cần truyền thêm một biến tokend hoặc checksess để đảm bảo an toàn

Tham khảo cách mã hóa, giải mã tương tự https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/admin/authors/add.php#L269 , dòng 269, 277
Cách giải mã https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/modules/users/admin/getuserid.php#L165-L170

Để an toàn hơn nên thay `NV_CHECK_SESSION` bằng giá trị khác ví dụ `md5(NV_CHECK_SESSION . '-del-logs-all')`

2020-11-27 15:27 UTC, quocdatit commented
@hoaquynhtim99 
em đã tối ưu theo phương án anh hướng dẫn, em review lại lần nữa nha

2021-01-10 08:42 UTC, hoaquynhtim99 requested changes

2021-01-10 08:42 UTC, hoaquynhtim99 commented on src/admin/siteinfo/logs_del.php
> +            nv_htmlOutput($nv_Lang->getModule('log_del_error') . ' toang');
@quocdatit bạn check lại chỗ này nhé, ai chơi chữ `toang` vào code. Với lại tham số `$where_str` truyền vào từ post data nó có khả năng không đúng chuẩn dẫn tới throw Exception, cho nên dù có dùng lên if thì nó không tác dụng.

Mình đề xuất sửa lại như sau:

```php
try {
    $db->query('DELETE FROM ' . $db_config['prefix'] . '_logs WHERE ' . $where_str);
    $nv_Cache->delMod($module_name);
    nv_insert_logs(NV_LANG_DATA, $module_name, $nv_Lang->getModule('log_empty_log_filter'), str_replace('AND', ',', $where_str), $admin_info['userid']);
    nv_htmlOutput('OK');
} catch (Exception $e) {
    trigger_error(print_r($e, true));
    nv_htmlOutput($nv_Lang->getModule('log_del_error'));
}
```

2021-01-10 08:42 UTC, hoaquynhtim99 commented on src/includes/language/vi/admin_siteinfo.php
> +$lang_module['log_empty_log_filter'] = 'Xóa nhật kí hệ thống theo điều kiện';
@quocdatit chỗ này có ngôn ngữ tiếng Anh, Pháp nữa nên bạn thêm cho cả 2 cái đó nhé (có thể dùng Google dịch)

2021-01-27 07:52 UTC, quocdatit commented
@hoaquynhtim99 done hết rồi anh

2021-01-27 09:11 UTC, hoaquynhtim99 commented
Ngon rồi bạn

2021-01-27 09:11 UTC, merged